### ISSUE TITLE
To Do list: add & remove

### ISSUE THREAD

**Issue by Camilovelag** [JonahKayizzi/TO-DO-LIST-app#4]
# Good day, @JonahKayizzi ! 🌤️

Your app looks pretty good, but in order to improve it, I would like to suggest the following changes:

![done](https://media.giphy.com/media/z3piokwf0WPH81MOhu/giphy.gif)

## 🛠️ Changes to do

✔️  Add a default value for the `complete` property:
`constructor(desc, complete = false, idx)`

https://github.com/JonahKayizzi/TO-DO-LIST-app/blob/3bc63e801c5b1093710aef0c723cfaba6af4be4a/src/modules/Task.js#L1-L7

### Optional suggestions

☑️ Reduce app width size to improve UI/UX experience.

Happy coding!👏👏👏

**Comment by JonahKayizzi** [comment]
Implemented
