### ISSUE TITLE
Peer to peer code review - Testing with JEST Framework

### ISSUE THREAD

**Issue by JonahKayizzi** [JonahKayizzi/TO-DO-LIST-app#8]

**Comment by rebaz36** [comment]
# great work @JonahKayizzi all functionalities are implemented correctly ✅ 

- I loved the way you approached the local storage mocks nice methods
- followed Js Best practices
- used pure functions whenever possible

## keep up the good work ✔️ 

![image](https://user-images.githubusercontent.com/66506429/194575701-f4cc59d3-95a6-4487-8eb8-f13816e22481.gif)

**Comment by Enekwestanley** [comment]
Great work on the test :heavy_check_mark:
good JS practice :heavy_check_mark:

Nice job

**Comment by JonahKayizzi** [comment]
Thanks for the review
